In [20]:
# Use iris flower dataset from sklearn library and use cross_val_score against following models 
# to measure the performance of each. In the end figure out the model with best performance,
# Logistic Regression
# SVM
# Decision Tree
# Random Forest

In [21]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
iris = load_iris()

In [22]:
# Logistic Regression
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
np.average(l_scores)

np.float64(0.9733333333333334)

In [24]:
# Decision Tree
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [25]:
np.average(d_scores)

np.float64(0.9666666666666668)

In [26]:
# Support Vector Machine (SVM)
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [27]:
np.average(s_scores)

np.float64(0.9666666666666666)

In [28]:
# Random Forest
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [29]:
np.average(r_scores)

np.float64(0.9533333333333334)